name: CI

on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: rm yarn.lock && yarn install

      - name: Test
        run: yarn test

      - name: Build
        env:
          REACT_APP_OWM_API_KEY: ${{ secrets.REACT_APP_OWM_API_KEY }}
          REACT_APP_FLICKR_API_KEY: ${{ secrets.REACT_APP_FLICKR_API_KEY }}
        run: yarn build

      - name: Publish
        uses: oleksiyrudenko/gha-git-credentials@v1
        with:
          name: 'Bruno Cechet'
          email: 'brunocechet@gmail.com'
        env:
          REACT_APP_OWM_API_KEY: ${{ secrets.REACT_APP_OWM_API_KEY }}
          REACT_APP_FLICKR_API_KEY: ${{ secrets.REACT_APP_FLICKR_API_KEY }}
        run: yarn deploy
